[pytest]
testpaths = Automation_TestCase

python_files = *.py

markers =
    positive: Positive Testcase
    negative: Negative Testcase
    smoke: Smoke Test
    regression: Regression Test
    klaim: klaim <odule
    subrogasi: Subrogasi Module
    akseptasi: Akseptasi Module
    